(()=>{
const bank=(window.EXS217_MOVEMENTS||[]).map(x=>({...x,type:"Cardio",custom:false}));
const cats=["All","Cycle","Battle Ropes","Balls","Cones","Ladders","Step","Plyometrics","Bodyweight"];
let category="All",custom=[],selected=[],blocks=[],nextBlock=1,nextItem=1,dragItem=null;
const resources={"Cycle":"https://www.keiser.com/support/articles/m3i-indoor-bike-set-up","Battle Ropes":"https://www.acefitness.org/resources/everyone/exercise-library/equipment/heavy-ropes/","Balls":"https://www.acefitness.org/resources/everyone/exercise-library/equipment/medicine-ball/","Cones":"https://www.acefitness.org/resources/everyone/exercise-library/equipment/cones/","Ladders":"https://www.acefitness.org/resources/everyone/exercise-library/equipment/ladder/","Step":"https://www.acefitness.org/resources/everyone/exercise-library/equipment/raised-platform-box/","Plyometrics":"https://www.acefitness.org/resources/everyone/exercise-library/equipment/raised-platform-box/","Bodyweight":"https://www.acefitness.org/resources/everyone/exercise-library/equipment/no-equipment/"};
function equipmentFor(x){if(x.custom)return x.category||"Student Added"; if(x.category==="Cycle")return "Bike";if(x.category==="Battle Ropes")return "Battle Ropes";if(x.category==="Balls")return "Ball";if(x.category==="Cones")return "Cones";if(x.category==="Ladders")return "Agility Ladder";if(x.category==="Step")return "Step";if(x.category==="Plyometrics")return /box|depth/i.test(x.name)?"Plyo Box":"No Equipment";return "No Equipment"}
function equipIcon(eq){const common=`viewBox="0 0 48 40" aria-hidden="true"`;if(eq==="Bike")return `<svg ${common}><circle cx="11" cy="29" r="8"/><circle cx="37" cy="29" r="8"/><path d="M11 29l9-15 8 15H11zm9-15h10l7 15M18 10h7M30 9h7"/></svg>`;if(eq==="Battle Ropes")return `<svg ${common}><path d="M3 29c7-18 14 18 21 0s14 18 21 0M3 22c7-18 14 18 21 0s14 18 21 0"/></svg>`;if(eq==="Ball")return `<svg ${common}><circle cx="24" cy="20" r="14"/><path d="M13 12c7 3 15 3 22 0M13 28c7-3 15-3 22 0M24 6c-5 8-5 20 0 28M24 6c5 8 5 20 0 28"/></svg>`;if(eq==="Cones")return `<svg ${common}><path d="M16 31h16L25 8h-2L16 31zm-3 0h22v5H13zM20 20h8"/></svg>`;if(eq==="Agility Ladder")return `<svg ${common}><path d="M8 5v30M40 5v30M8 10h32M8 18h32M8 26h32M8 34h32"/></svg>`;if(eq==="Step")return `<svg ${common}><path d="M7 28h34v8H7zM12 22h24v6H12z"/></svg>`;if(eq==="Plyo Box")return `<svg ${common}><path d="M10 12h28v24H10zM10 12l7-7h25v24l-4 7M38 12l4-7"/></svg>`;return `<svg ${common}><circle cx="24" cy="8" r="4"/><path d="M24 12v12M15 18l9-4 9 4M24 24l-8 12M24 24l8 12"/></svg>`}
function equipBadge(x){const eq=equipmentFor(x);return `<div><div class="equipment-badge">${equipIcon(eq)}</div><div class="equipment-label">${esc(eq)}</div></div>`}
const $=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const allMoves=()=>[...bank,...custom],getMove=id=>allMoves().find(x=>x.id===id);
function renderTabs(){const n=$("#tabs");n.innerHTML="";cats.forEach(c=>{const b=document.createElement("button");b.type="button";b.textContent=c;b.className=c===category?"active":"";b.onclick=()=>{category=c;renderTabs();renderLibrary()};n.appendChild(b)})}
function filtered(){const q=$("#search").value.toLowerCase().trim(),imp=$("#impact").value,eq=$("#equipment").value;return allMoves().filter(x=>(category==="All"||x.category===category||x.custom)&&(!imp||x.impact===imp)&&(!eq||equipmentFor(x)===eq)&&(!q||(JSON.stringify(x)+" "+equipmentFor(x)).toLowerCase().includes(q)))}
function renderLibrary(){const arr=filtered();$("#resultCount").textContent=`Showing ${arr.length} movement${arr.length===1?"":"s"}.`;const n=$("#cards");n.innerHTML="";arr.forEach(x=>{const row=document.createElement("article");row.className="movement-row";const chosen=selected.includes(x.id);row.innerHTML=`<div class="movement-summary"><div class="movement-identity">${equipBadge(x)}<div><h3>${esc(x.name)} ${x.custom?'<span class="tag">Student Added</span>':""}</h3><div class="meta">${esc(x.category)} · ${esc(x.impact)} impact · ${esc(x.complexity)} complexity</div><p>${esc(x.emphasis||x.type)}</p></div></div><div class="row-actions"><button type="button" class="details">View Details ▾</button><button type="button" class="add ${chosen?'chosen':''}">${chosen?'Chosen ✓':'+ Choose'}</button></div></div><div class="movement-details" hidden><p><strong>Equipment:</strong> ${esc(equipmentFor(x))}</p><p><strong>Coach it:</strong> ${(x.cues||["Use appropriate technique and coaching cues."]).map(esc).join(" • ")}</p><p><strong>↓ Reduce demand:</strong> ${Array.isArray(x.reduce)?x.reduce.map(esc).join(" • "):esc(x.reduce||"Not entered")}</p><p><strong>↑ Increase demand:</strong> ${Array.isArray(x.increase)?x.increase.map(esc).join(" • "):esc(x.increase||"Not entered")}</p>${x.watch&&x.watch.length?`<p><strong>Watch for:</strong> ${x.watch.map(esc).join(" • ")}</p>`:""}${!x.custom&&resources[x.category]?`<a class="resource-link" href="${resources[x.category]}" target="_blank" rel="noopener">External Technique Resource ↗</a><p class="small">Optional outside reference. Use the EXS217 coaching guidance above for course expectations.</p>`:""}${x.custom?'<p class="small">Student-added classification. You are responsible for how this exercise is programmed.</p>':""}</div>`;
const d=row.querySelector(".details"),detail=row.querySelector(".movement-details");d.onclick=()=>{detail.hidden=!detail.hidden;d.textContent=detail.hidden?"View Details ▾":"Hide Details ▴"};row.querySelector(".add").onclick=()=>{if(!selected.includes(x.id))selected.push(x.id);renderLibrary();renderSelected()};n.appendChild(row)})}
function renderSelected(){const n=$("#selectedList");n.innerHTML="";$("#selCount").textContent=selected.length?`(${selected.length})`:"";$("#selectedEmpty").hidden=selected.length>0;selected.map(getMove).filter(Boolean).forEach(m=>{const r=document.createElement("div");r.className="selected-row";r.innerHTML=`<div><strong>${esc(m.name)}</strong><span>${esc(m.type||"Cardio")}${m.custom?' · Student Added':''}</span></div><div class="selected-actions"><select aria-label="Choose block for ${esc(m.name)}"><option value="">Add to block…</option>${blocks.map(b=>`<option value="${b.id}">${esc(b.title)}</option>`).join("")}</select><button type="button" class="place">Add</button><button type="button" class="remove" aria-label="Remove ${esc(m.name)} from My Exercises">×</button></div>`;r.querySelector(".place").onclick=()=>{const bid=r.querySelector("select").value;if(!bid){alert("Choose a block first.");return}addToBlock(bid,m.id)};r.querySelector(".remove").onclick=()=>{selected=selected.filter(id=>id!==m.id);renderLibrary();renderSelected()};n.appendChild(r)})}
function newBlock(){return{id:"b"+(nextBlock++),title:`Block ${blocks.length+1}`,format:"Timed Station / Block",duration:4,work:30,recovery:15,rounds:3,transition:0,items:[]}}
function addBlock(){blocks.push(newBlock());renderBlocks();renderSelected();updateTime()}
function addToBlock(bid,mid){const b=blocks.find(x=>x.id===bid);if(!b)return;b.items.push({uid:"i"+(nextItem++),movementId:mid,reps:""});renderBlocks();updateTime()}
function blockMinutes(b){if(b.format==="Timed Intervals"){return b.items.length*((+b.work||0)+(+b.recovery||0))*(+b.rounds||1)/60}return +b.duration||0}
function renderBlocks(){const n=$("#blocks");n.innerHTML="";if(!blocks.length){n.innerHTML='<div class="empty">Add a block or station to begin.</div>';return}blocks.forEach((b,bi)=>{const sec=document.createElement("article");sec.className="workout-block";sec.innerHTML=`<div class="block-head"><input class="title" aria-label="Block title" value="${esc(b.title)}"><div class="block-actions no-print"><button type="button" class="duplicate">Duplicate</button><button type="button" class="delete">Delete</button></div></div><div class="block-grid"><label>Format<select class="format"><option ${b.format==="Timed Intervals"?'selected':''}>Timed Intervals</option><option ${b.format==="Timed Station / Block"?'selected':''}>Timed Station / Block</option><option ${b.format==="Reps / Rounds"?'selected':''}>Reps / Rounds</option><option ${b.format==="Continuous"?'selected':''}>Continuous</option><option ${b.format==="Instructor / Group-Led"?'selected':''}>Instructor / Group-Led</option></select></label><span class="format-fields"></span><label>Transition after block (min)<input class="transition" type="number" min="0" max="30" step="0.5" value="${b.transition}"></label></div><div class="dropzone"><p class="drop-hint">Add exercises from My Exercises. Drag exercises here to reorder or move them between blocks.</p><div class="block-items"></div></div>`;
const ff=sec.querySelector(".format-fields");function fields(){if(b.format==="Timed Intervals")ff.innerHTML=`<label>Work (sec)<input class="work" type="number" min="5" max="600" value="${b.work}"></label><label>Recovery (sec)<input class="recovery" type="number" min="0" max="600" value="${b.recovery}"></label><label>Rounds<input class="rounds" type="number" min="1" max="20" value="${b.rounds}"></label>`;else if(b.format==="Reps / Rounds")ff.innerHTML=`<label>Estimated block time (min)<input class="duration" type="number" min="1" max="60" step="0.5" value="${b.duration}"></label><label>Rounds<input class="rounds" type="number" min="1" max="20" value="${b.rounds}"></label>`;else ff.innerHTML=`<label>Block duration (min)<input class="duration" type="number" min="1" max="60" step="0.5" value="${b.duration}"></label>`;ff.querySelectorAll("input").forEach(el=>el.oninput=()=>{b[el.className]=el.value;updateTime()})}
sec.querySelector(".title").oninput=e=>{b.title=e.target.value;renderSelected()};sec.querySelector(".format").onchange=e=>{b.format=e.target.value;fields();renderBlockItems(sec,b);updateTime()};sec.querySelector(".transition").oninput=e=>{b.transition=e.target.value;updateTime()};sec.querySelector(".duplicate").onclick=()=>{const cp=JSON.parse(JSON.stringify(b));cp.id="b"+(nextBlock++);cp.title=b.title+" Copy";cp.items=cp.items.map(i=>({...i,uid:"i"+(nextItem++)}));blocks.splice(bi+1,0,cp);renderBlocks();renderSelected();updateTime()};sec.querySelector(".delete").onclick=()=>{blocks.splice(bi,1);renderBlocks();renderSelected();updateTime()};fields();renderBlockItems(sec,b);setupDrop(sec,b);n.appendChild(sec)});updateTime()}
function renderBlockItems(sec,b){const n=sec.querySelector(".block-items");n.innerHTML="";b.items.forEach((it,idx)=>{const m=getMove(it.movementId);if(!m)return;const row=document.createElement("div");row.className="workout-item";row.draggable=true;row.innerHTML=`<span class="drag" aria-hidden="true">☰</span><div class="item-main"><strong>${esc(m.name)}</strong><span>${esc(m.type||"Cardio")}${m.custom?' · Student Added':''}</span></div>${(b.format==="Reps / Rounds"||b.format==="Timed Station / Block")?`<label class="reps">Reps / instruction<input type="text" value="${esc(it.reps)}" placeholder="e.g., 10/side"></label>`:""}<div class="item-actions no-print"><select aria-label="Move ${esc(m.name)}"><option value="">Move…</option>${blocks.map(x=>`<option value="${x.id}">${esc(x.title)}</option>`).join("")}</select><button type="button" class="remove-item" aria-label="Remove ${esc(m.name)}">×</button></div>`;const rep=row.querySelector(".reps input");if(rep)rep.oninput=e=>it.reps=e.target.value;row.querySelector("select").onchange=e=>{const dest=blocks.find(x=>x.id===e.target.value);if(!dest||dest.id===b.id)return;b.items.splice(idx,1);dest.items.push(it);renderBlocks()};row.querySelector(".remove-item").onclick=()=>{b.items.splice(idx,1);renderBlocks()};row.addEventListener("dragstart",()=>{dragItem={from:b.id,uid:it.uid};row.classList.add("dragging")});row.addEventListener("dragend",()=>{dragItem=null;row.classList.remove("dragging")});row.addEventListener("dragover",e=>e.preventDefault());row.addEventListener("drop",e=>{e.preventDefault();moveDragged(b.id,it.uid)});n.appendChild(row)})}
function moveDragged(toBid,beforeUid=null){if(!dragItem)return;const from=blocks.find(x=>x.id===dragItem.from),to=blocks.find(x=>x.id===toBid);if(!from||!to)return;const ix=from.items.findIndex(x=>x.uid===dragItem.uid);if(ix<0)return;const [item]=from.items.splice(ix,1);let pos=beforeUid?to.items.findIndex(x=>x.uid===beforeUid):-1;if(pos<0)to.items.push(item);else to.items.splice(pos,0,item);renderBlocks()}
function setupDrop(sec,b){const z=sec.querySelector(".dropzone");z.addEventListener("dragover",e=>{e.preventDefault();z.classList.add("active-drop")});z.addEventListener("dragleave",()=>z.classList.remove("active-drop"));z.addEventListener("drop",e=>{e.preventDefault();z.classList.remove("active-drop");moveDragged(b.id)})}
function updateEquipment(){const used=[];blocks.forEach(b=>b.items.forEach(i=>{const m=getMove(i.movementId);if(m){const e=equipmentFor(m);if(!used.includes(e))used.push(e)}}));$("#equipmentSummary").innerHTML=`<strong>Equipment used:</strong> ${used.length?used.map(esc).join(" · "):"None added yet."}`}
function updateTime(){const total=+$("#totalTime").value||0;const main=blocks.reduce((s,b)=>s+blockMinutes(b)+(+b.transition||0),0);$("#mainTime").textContent=`${Math.round(main*10)/10} min`;$("#remainingTime").textContent=`${Math.round((total-main)*10)/10} min`;$("#remainingTime").classList.toggle("over",main>total);updateEquipment()}
function buildPrintReport(){
const total=+$("#totalTime").value||0,main=blocks.reduce((sum,b)=>sum+blockMinutes(b)+(+b.transition||0),0),num=n=>String(Math.round(n*10)/10);
let elapsed=0;
const sections=blocks.map((b,index)=>{
const duration=blockMinutes(b),start=elapsed;elapsed+=duration+(+b.transition||0);
const timing=b.format==="Timed Intervals"?`${b.work} sec work / ${b.recovery} sec recovery · ${b.rounds} rounds`:b.format==="Reps / Rounds"?`${b.rounds} rounds · estimated time`:"Entered duration";
return `<article class="report-block"><h2>${index+1}. ${esc(b.title)}</h2><p class="report-meta">${esc(b.format)} · ${esc(timing)}</p><p class="report-meta">Main-workout timeline: ${num(start)}–${num(start+duration)} min · Block: ${num(duration)} min · Transition after: ${esc(b.transition)} min</p><table><thead><tr><th scope="col">Exercise</th><th scope="col">Equipment</th><th scope="col">Reps / instruction</th></tr></thead><tbody>${b.items.length?b.items.map(it=>{const m=getMove(it.movementId);return `<tr><td>${esc(m?.name||"Exercise unavailable")}<span class="report-meta">${esc(m?.type||"Cardio")}</span></td><td>${esc(m?equipmentFor(m):"—")}</td><td>${esc((b.format==="Reps / Rounds"||b.format==="Timed Station / Block")?it.reps||"Not entered":"—")}</td></tr>`}).join(""):'<tr><td colspan="3">No exercises entered.</td></tr>'}</tbody></table></article>`
}).join("");
let report=$("#printReport");if(!report){report=document.createElement("div");report.id="printReport";document.body.appendChild(report)}
report.innerHTML=`<div class="report-heading"><p class="report-kicker">EXS217 · CARDIORESPIRATORY TRAINING</p><h1>Main Workout Plan</h1></div><table class="report-summary"><tbody><tr><th>Teaching time available</th><td>${num(total)} min</td><th>Main workout + transitions</th><td>${num(main)} min</td></tr><tr><th>Time remaining</th><td colspan="3">${num(total-main)} min${main>total?' · Exceeds available teaching time':''}</td></tr></tbody></table><p>${$("#equipmentSummary").innerHTML}</p>${sections||'<p>No workout blocks entered.</p>'}<p class="report-footnote">This report covers the main workout only. Plan the introduction, demonstrations, warm-up, cool-down, intensity monitoring, and participant modifications separately. Timeline values begin at the start of the main workout; station sequencing follows the entries in this builder.</p>`;
}
window.addEventListener("beforeprint",buildPrintReport);
function openCustom(show){$("#customForm").hidden=!show;if(show)$("#customName").focus()}
$("#openCustom").onclick=()=>openCustom(true);$("#cancelCustom").onclick=()=>openCustom(false);$("#saveCustom").onclick=()=>{const name=$("#customName").value.trim();if(!name){$("#customError").textContent="Enter an exercise name.";return}const id="custom-"+Date.now();custom.push({id,name,type:$("#customType").value,category:$("#customEquipment").value.trim()||"Student Added",impact:$("#customImpact").value,complexity:"Student choice",emphasis:$("#customType").value,cues:[],reduce:[],increase:[],custom:true});selected.push(id);$("#customName").value="";$("#customEquipment").value="";$("#customError").textContent="";openCustom(false);renderLibrary();renderSelected()};
$("#search").oninput=renderLibrary;$("#impact").onchange=renderLibrary;$("#equipment").onchange=renderLibrary;$("#addBlock").onclick=addBlock;$("#totalTime").oninput=updateTime;$("#print").onclick=()=>{buildPrintReport();window.print()};
renderTabs();blocks=[newBlock()];renderLibrary();renderBlocks();renderSelected();updateTime();
})();
